CREATE SEQUENCE SERIAL --criar trigger para auto incremento das PK's
  START WITH 1
  INCREMENT BY 2
  NOCACHE
  NOCYCLE
  ;

CREATE TABLE PATROCINADOR(
    ID INT,
    NOME VARCHAR2(60),
    TIPO VARCHAR2(60) NOT NULL,
    
    CONSTRAINT PATROCINADOR_PK PRIMARY KEY(ID),
    CONSTRAINT PATROCINADOR_UN UNIQUE(NOME)
);

CREATE TABLE ATLETA(
    PASSAPORTE INT,
    NOME VARCHAR2(60) NOT NULL,
    DATA_NASC DATE NOT NULL,
    
    CONSTRAINT ATLETA_PK PRIMARY KEY(PASSAPORTE),
    CONSTRAINT ATLETA_UN UNIQUE(NOME)
);

CREATE TABLE PAIS(
    ID INT,
    NOME VARCHAR2(60) NOT NULL,
    CONTINENTE CHAR(2),
    POPULACAO INTEGER DEFAULT 0,
    
    CONSTRAINT PAIS_PK PRIMARY KEY(ID),
    CONSTRAINT PAIS_UN UNIQUE(NOME),
    CONSTRAINT PAIS_CK CHECK(UPPER(CONTINENTE) IN('SA', 'CA', 'NA', 'EU', 'AF', 'AS'))
);

CREATE TABLE OLIMPIADA(
    ANO INT,
    SEDE VARCHAR2(30) NOT NULL,
    N_MODALIDADES INT DEFAULT 1,
    ORG_GERAL INT,
    
    CONSTRAINT OLIMPIADA_PK PRIMARY KEY(ANO),
    CONSTRAINT OLIMPIADA_UN UNIQUE (ORG_GERAL),
    CONSTRAINT ANO_CK CHECK(ANO >= 1986 AND ANO <= 2024)
);
--drop table olimpiada


CREATE TABLE ORGANIZADOR_GERAL(
    ID INT,
    NOME VARCHAR2(60) NOT NULL,
    DATA_NASC DATE,
    
    CONSTRAINT ORG_PK PRIMARY KEY(ID),
    CONSTRAINT ORG_UN UNIQUE(NOME),
    CONSTRAINT ORG_FK FOREIGN KEY(ID) REFERENCES OLIMPIADA(ORG_GERAL) ON DELETE CASCADE
);


CREATE TABLE MODALIDADE(
     ID INT,
     NOME VARCHAR(60) NOT NULL,
     N_COMPETIDORES INT DEFAULT 2,--minimo para haver competição
     GENERO CHAR(1) NOT NULL,
     
     CONSTRAINT MODALIDADE_PK PRIMARY KEY(ID),
     CONSTRAINT MODALIDADE_UN UNIQUE(NOME, GENERO),
     CONSTRAINT MODALIDADE_CK CHECK(UPPER(GENERO) IN('M','F'))
     );
     
CREATE TABLE MIDIA(
    ID INT,
    NOME VARCHAR(60) NOT NULL,
    
    CONSTRAINT MIDIA_PK PRIMARY KEY(ID),
    CONSTRAINT MIDIA_UN UNIQUE(NOME)
);

CREATE TABLE EQUIPE(
    NOME VARCHAR(60),
    PAIS INT,
    ANO INT,
    
    CONSTRAINT EQUIPE_PK PRIMARY KEY(NOME, PAIS, ANO),
    CONSTRAINT EQUIPE_FK FOREIGN KEY(PAIS) REFERENCES PAIS(ID) ON DELETE CASCADE
);

CREATE TABLE LOCAL(
    ID INT,
    NOME VARCHAR2(60),
    CAPACIDADE INT DEFAULT 0,
    ZIPCODE VARCHAR2(20),
    
    CONSTRAINT LOCAL_PK PRIMARY KEY(ID),
    CONSTRAINT LOCAL_UN UNIQUE(NOME, ZIPCODE),
    CONSTRAINT LOCAL_CK CHECK(CAPACIDADE >= 0)
    );
    
CREATE TABLE PAIS_OLIMPIADA(
    PAIS INT,
    OLIMPIADA INT,
    
    CONSTRAINT PO_PK PRIMARY KEY(PAIS, OLIMPIADA),
    CONSTRAINT PO_FK1 FOREIGN KEY(PAIS) REFERENCES PAIS(ID) ON DELETE CASCADE,
    CONSTRAINT PO_FK2 FOREIGN KEY(OLIMPIADA) REFERENCES OLIMPIADA(ANO) ON DELETE CASCADE
 
);

CREATE TABLE ATLETA_EQUIPE(
    ATLETA INT,
    NOME_EQUIPE VARCHAR(60),
    EQUIPE_PAIS INT,
    EQUIPE_ANO INT,
    
    CONSTRAINT AE_PK PRIMARY KEY(ATLETA, NOME_EQUIPE, EQUIPE_PAIS, EQUIPE_ANO),
    CONSTRAINT AE_FK1 FOREIGN KEY(ATLETA) REFERENCES ATLETA(PASSAPORTE) ON DELETE CASCADE,
    CONSTRAINT AE_FK2 FOREIGN KEY(NOME_EQUIPE, EQUIPE_PAIS, EQUIPE_ANO) REFERENCES EQUIPE(NOME, PAIS, ANO) ON DELETE CASCADE
);

CREATE TABLE EQUIPE_MODALIDADE(
    EQUIPE_NOME VARCHAR(60),
    EQUIPE_PAIS INT,
    EQUIPE_ANO INT,
    MODALIDADE INT,
    
    CONSTRAINT EM_PK PRIMARY KEY(EQUIPE_NOME, EQUIPE_PAIS, EQUIPE_ANO, MODALIDADE),
    CONSTRAINT EM_FK1 FOREIGN KEY(EQUIPE_NOME, EQUIPE_PAIS, EQUIPE_ANO) REFERENCES EQUIPE(NOME, PAIS, ANO) ON DELETE CASCADE,
    CONSTRAINT EM_FK2 FOREIGN KEY(MODALIDADE) REFERENCES MODALIDADE(ID) ON DELETE CASCADE
);

CREATE TABLE PATROCINIO_ATLETA(
    PATROCINADOR INT,
    ATLETA INT,
    INICIO_CONTRATO DATE,
    TEMPO_VIGENCIA INT NOT NULL,
    VALOR_CONTRATO DECIMAL(12, 2),
    
    CONSTRAINT PA_PK PRIMARY KEY(PATROCINADOR, ATLETA, INICIO_CONTRATO),
    CONSTRAINT PA_FK1 FOREIGN KEY(PATROCINADOR) REFERENCES PATROCINADOR(ID) ON DELETE CASCADE,
    CONSTRAINT PA_FK2 FOREIGN KEY(ATLETA) REFERENCES ATLETA(PASSAPORTE) ON DELETE CASCADE,
    CONSTRAINT PA_CK2 CHECK(TEMPO_VIGENCIA > 0 AND VALOR_CONTRATO > 0.00)
);

CREATE TABLE DISPUTA(
    ID INT,
    HORA DECIMAL(3,1) NOT NULL,
    DATA DATE NOT NULL,
    MODALIDADE INT NOT NULL,
    PAIS1 INT NOT NULL,
    PAIS2 INT NOT NULL,
    VENCEDOR INT NOT NULL,
    LOCAL INT, 
    OLIMPIADA INT,
    
    CONSTRAINT DISPUTA_PK PRIMARY KEY(ID),
    CONSTRAINT DISPUTA_UN UNIQUE(MODALIDADE, PAIS1, PAIS2, OLIMPIADA),
    CONSTRAINT DISPUTA_FK1 FOREIGN KEY(MODALIDADE) REFERENCES MODALIDADE(ID) ON DELETE CASCADE,
    CONSTRAINT DISPUTA_FK2 FOREIGN KEY(PAIS1) REFERENCES PAIS(ID) ON DELETE CASCADE,
    CONSTRAINT DISPUTA_FK3 FOREIGN KEY(PAIS2) REFERENCES PAIS(ID) ON DELETE CASCADE,
    CONSTRAINT DISPUTA_FK4 FOREIGN KEY(OLIMPIADA) REFERENCES OLIMPIADA(ANO) ON DELETE CASCADE,
    CONSTRAINT DISPUTA_FK5 FOREIGN KEY(LOCAL) REFERENCES LOCAL(ID) ON DELETE CASCADE,
    CONSTRAINT DISPUTA_CK CHECK(VENCEDOR = PAIS1 OR VENCEDOR = PAIS2)
);

CREATE TABLE TV(
    NOME VARCHAR(60),
    CANAL INT NOT NULL,
    ABERTA_FECHADA VARCHAR(7) NOT NULL,
    
    CONSTRAINT TV_PK PRIMARY KEY(NOME),
    CONSTRAINT TV_UN UNIQUE(CANAL),
    CONSTRAINT TV_FK FOREIGN KEY(NOME) REFERENCES MIDIA(NOME) ON DELETE CASCADE,
    CONSTRAINT TV_CK1 CHECK(CANAL > 0),
    CONSTRAINT TV_CK2 CHECK(UPPER(ABERTA_FECHADA) IN ('ABERTA', 'FECHADA'))
);

CREATE TABLE TRANSMISSAO_TV(
    DISPUTA INT,
    MIDIA INT,
    
    CONSTRAINT T_TV_PK PRIMARY KEY(DISPUTA, MIDIA),
    CONSTRAINT T_TV_FK1 FOREIGN KEY(DISPUTA) REFERENCES DISPUTA(ID) ON DELETE CASCADE,
    CONSTRAINT T_TV_FK1 FOREIGN KEY(MIDIA) REFERENCES MIDIA(ID) ON DELETE CASCADE
);

CREATE TABLE RADIO(
    NOME VARCHAR(60),
    FREQUENCIA DECIMAL(5,2) NOT NULL,
    
    CONSTRAINT TV_PK PRIMARY KEY(NOME),
    CONSTRAINT TV_UN UNIQUE(FREQUENCIA),
    CONSTRAINT TV_FK FOREIGN KEY(NOME) REFERENCES MIDIA(NOME) ON DELETE CASCADE,
    CONSTRAINT CANAL_CK CHECK(FREQUENCIA > 0.00)
);

CREATE TABLE STREAMING(
    NOME VARCHAR(60),
    URL VARCHAR2(60) NOT NULL,
    ASSINATURA_GRATUITO VARCHAR(10) NOT NULL,
    
    CONSTRAINT STREAMING_PK PRIMARY KEY(NOME),
    CONSTRAINT STREAMING_UN UNIQUE(URL),
    CONSTRAINT STREAMING_FK FOREIGN KEY(NOME) REFERENCES MIDIA(NOME) ON DELETE CASCADE,
    CONSTRAINT STREAMING_CK CHECK(UPPER(ASSINATURA_GRATUITO) IN ('ASSINATURA', 'GRATUITO'))
);





     
     



