INSERT INTO PATROCINADOR (ID, NOME, TIPO) 
VALUES (SEQ_PATROCINADOR_ID.NEXTVAL, 'Coca-Cola', 'Bebida');

INSERT INTO PATROCINADOR (ID, NOME, TIPO) 
VALUES (SEQ_PATROCINADOR_ID.NEXTVAL, 'Nike', 'Roupas Esportivas');

INSERT INTO PAIS (ID, NOME, CONTINENTE, POPULACAO) 
VALUES (SEQ_PAIS_ID.NEXTVAL, 'Brasil', 'SA', DEFAULT);

INSERT INTO PAIS (ID, NOME, CONTINENTE, POPULACAO) 
VALUES (SEQ_PAIS_ID.NEXTVAL, 'Japão', 'AS', 125000000);

INSERT INTO ATLETA (PASSAPORTE, NOME, DATA_NASC, IDADE) 
VALUES (1001, 'Maria Silva', TO_DATE('12-05-1995', 'DD-MM-YYYY'), 29);

INSERT INTO ATLETA (PASSAPORTE, NOME, DATA_NASC, IDADE) 
VALUES (1002, 'John Doe', TO_DATE('23-11-1988', 'DD-MM-YYYY'), 35);

INSERT INTO OLIMPIADA (ANO, SEDE, N_MODALIDADES, ORG_GERAL) 
VALUES (2020, 'Tóquio', 33, 2);

INSERT INTO OLIMPIADA (ANO, SEDE, N_MODALIDADES, ORG_GERAL) 
VALUES (2016, 'Rio de Janeiro', DEFAULT, 1);

INSERT INTO ORGANIZADOR_GERAL (ID, NOME, DATA_NASC) 
VALUES (1, 'Comitê Olímpico Brasileiro', TO_DATE('05-08-1980', 'DD-MM-YYYY'));

INSERT INTO ORGANIZADOR_GERAL (ID, NOME, DATA_NASC) 
VALUES (2, 'Comitê Olímpico Internacional', NULL);

INSERT INTO MODALIDADE (ID, NOME, N_COMPETIDORES, GENERO) 
VALUES (SEQ_MODALIDADE_ID.NEXTVAL, 'Futebol', DEFAULT, 'M');

INSERT INTO MODALIDADE (ID, NOME, N_COMPETIDORES, GENERO) 
VALUES (SEQ_MODALIDADE_ID.NEXTVAL, 'Natação', 8, 'F');

INSERT INTO MIDIA (ID, NOME) 
VALUES (SEQ_MIDIA_ID.NEXTVAL, 'TV Globo');

INSERT INTO MIDIA (ID, NOME) 
VALUES (SEQ_MIDIA_ID.NEXTVAL, 'ESPN');

INSERT INTO LOCAL (ID, NOME, CAPACIDADE, ZIPCODE) 
VALUES (SEQ_LOCAL_ID.NEXTVAL, 'Maracanã', DEFAULT, '20021-203');

INSERT INTO LOCAL (ID, NOME, CAPACIDADE, ZIPCODE) 
VALUES (SEQ_LOCAL_ID.NEXTVAL, 'Estádio Olímpico', 60000, '136-0075');
SELECT * FROM MODALIDADE

INSERT INTO DISPUTA (ID, HORA, DATA, MODALIDADE, PAIS1, PAIS2, VENCEDOR, LOCAL, OLIMPIADA) 
VALUES (SEQ_DISPUTA_ID.NEXTVAL, 15.5, TO_DATE('21-08-2016', 'DD-MM-YYYY'), 21, 13, 16, 13, 29, 2016);

INSERT INTO DISPUTA (ID, HORA, DATA, MODALIDADE, PAIS1, PAIS2, VENCEDOR, LOCAL, OLIMPIADA) 
VALUES (SEQ_DISPUTA_ID.NEXTVAL, 10.0, TO_DATE('23-07-2021', 'DD-MM-YYYY'), 21, 16, 13, 16, 36, 2020);
